### ISSUE TITLE
iOS 8 지원

### ISSUE THREAD

**Issue by seapy** [trilliwon/JNaturalKorean#11]
좋은걸 공개해주셔서 잘 사용하고 있습니다.

iOS 8 지원을 다시 할수는 없을까요?
UI 라이브러리와 다르게 이 라이브러리는 iOS 버전을 좀 낮은것까지 지원하더라도 괜찮지 않을까 싶어서요

**Comment by trilliwon** [comment]
오늘 수정할게요. 감사합니다

**Comment by trilliwon** [comment]
수정 완료했습니다. 1.0.1 버전은 iOS 8.0+ 지원합니다.

**Comment by seapy** [comment]
혹시나 해서 이슈 남긴건데 바로 지원해주시다니 감사합니다 ^^
